### ISSUE TITLE
New UI mockup

### ISSUE THREAD

**Issue by hughillustration** [EFForg/actioncenter-mobile#22]
Here's an idea!
![app-1b](https://cloud.githubusercontent.com/assets/10857936/6053334/efced744-ac92-11e4-8d7a-4e43c9b37306.png)

**Comment by SecUpwN** [comment]
Awesome work @hughillustration, I love it! :+1:

**Comment by SecUpwN** [comment]
@mfb, why have you just closed this without a word?
