### ISSUE TITLE
Add appropriate legal notices and license notices 

### ISSUE THREAD

**Issue by joshuagay** [EFForg/actioncenter-mobile#25]
A copyright and license notice should be added to the appropriate files. It should also specify whether the program is licensed AGPLv3-only or AGPLv3-or-later. See [pull request](https://github.com/EFForg/actioncenter-mobile/pull/24) for a suggested sample.

**Comment by mfb** [comment]
also added a copyright statement to the README so it's not just buried in a subdirectory.
