### ISSUE TITLE
Add Tab Navigation

### ISSUE THREAD

**Issue by maxateff** [EFForg/actioncenter-mobile#27]
EFF's Activism team would like three tabs in the mobile app: 'Action', 'News', and 'More'.  Users should be able to navigate between them with lateral swipes.
![screenshot from 2015-09-22 19 18 41](https://cloud.githubusercontent.com/assets/7452506/10036620/c8b82e36-615e-11e5-8999-2d59f3b4ad84.png)

**Comment by mfb** [comment]
Swipe navigation isn't working but I think this could be closed.
