### ISSUE TITLE
add senderID to the repo?

### ISSUE THREAD

**Issue by mfb** [EFForg/actioncenter-mobile#5]
I'm thinking we could add our sender ID to the repo - in config/production.json - so that anyone can compile an app that actually works.  Thus a customized app could still subscribe to receive notifications.

**Comment by sinak** [comment]
That's true, but won't users need to have Google Play installed to receive messages from GCM in any case? Still, probably worth doing.

**Comment by mfb** [comment]
Yes but it means someone could tweak/customize the app or add a feature and still use it the way it was intended. (Also allows for reproducible builds :)

**Comment by sinak** [comment]
That's true! Okay lets do it.

**Comment by mfb** [comment]
Note I haven't test reproducible builds yet, but this would at least be one more step there. Some info about that here: https://f-droid.org/wiki/page/Deterministic,_Reproducible_Builds
