### ISSUE TITLE
Remove hard dependency on GCM

### ISSUE THREAD

**Issue by danhawkes** [EFForg/actioncenter-mobile#6]
It looks like the app requires GCM to function. GCM has a dependency on the Google Play services framework (AKA 'the play store').

I suspect that a sizeable proportion of the audience the app intends to motivate into action are excluded by this requirement. In particular, I'm thinking of F-Droid users, and also users whose devices do not ship with the 'Google experience' (e.g. Xiaomi devices).

Proprietary push services are great for battery-efficient real-time notifications, but IMO 'real-time'  isn't really a requirement for the slow moving world of politics. Could a fall-back be implemented that periodically pulls notification updates from an EFF server?

**Comment by mfb** [comment]
Anyone want to dive in and research this? At first glance I'd say we would need a cordova plugin that implements android AlarmManager to setup periodic polling.

re: real-time notifications: Politics often moves at a glacial pace, but it can move disturbingly quickly when passing an unpopular law or voting on last-minute amendments.

**Comment by danhawkes** [comment]
Surprised there's not a plugin for that already - will have a look over the weekend to see if it's possible.

**Comment by picsi** [comment]
Anyway we can have a gradle flavor without GCM?
